{{- if .Values.elasticsearch.deployment.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "wazuh.elasticsearch.fullname" . }}-elasticsearch
  labels:
{{ include "labels" $ | indent 4 }}
    appComponent: Elasticsearch-StatefulSet
    app: {{ include "wazuh.elasticsearch.fullname" . }}-elasticsearch
  annotations:
{{ include "annotations" $ | indent 4 }}
    appComponent: Elasticsearch-StatefulSet
spec:
  serviceName: {{ include "appIdentifier" .Values.identifier }}-elasticsearch
  replicas: {{ .Values.elasticsearch.images.replicaCount }}
  updateStrategy:
    type: {{ .Values.elasticsearch.images.updateStrategy }}
  selector:
    matchLabels:
{{ include "labels" $ | indent 6 }}
      app: {{ include "wazuh.elasticsearch.fullname" . }}-elasticsearch
      role: master
  serviceName: {{ include "appIdentifier" .Values.identifier }}-wazuh-elasticsearch
  template:
    metadata:
      labels:
{{ include "labels" $ | indent 8 }}
        appComponent: Elasticsearch-StatefulSet
        app: {{ include "wazuh.elasticsearch.fullname" . }}-elasticsearch
        role: master
      annotations:
{{ include "annotations" $ | indent 8 }}
        appComponent: Elasticsearch-StatefulSet
{{- if .Values.vault.enabled }}
        vault.security.banzaicloud.io/vault-addr: {{ .Values.vault.security.vault_addr | quote }}
        vault.security.banzaicloud.io/vault-role: {{ .Values.vault.security.vault_role | quote }}
        vault.security.banzaicloud.io/vault-path: {{ .Values.vault.security.vault_path | quote }}
        vault.security.banzaicloud.io/vault-skip-verify: {{ .Values.vault.security.vault_skip_verify | quote }}
{{- end }}
    spec:
      # Set the wazuh-elasticsearch volume permissions so the elasticsearch user can use it
      volumes:
        - name: odfe-ssl-certs 
          secret:
            secretName: odfe-ssl-certs
        - name: elastic-odfe-conf
          configMap:
            name: {{ template "wazuh.elasticsearch.fullname" . }}-config
      initContainers:
        - name: volume-mount-hack
          image: busybox
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          command:
            - sh
            - "-c"
            - "chown -R 1000:1000 /usr/share/elasticsearch/data"
          volumeMounts:
            - name: wazuh-elasticsearch
              mountPath: /usr/share/elasticsearch/data
        - name: increase-the-vm-max-map-count
          image: busybox
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      containers:
        - name: wazuh-elasticsearch
          image: "{{ .Values.elasticsearch.images.repository }}:{{ .Values.elasticsearch.images.tag }}"
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
            - name: CLUSTER_NAME
              value: {{ .Values.elasticsearch.env.CLUSTER_NAME }}
            - name: NETWORK_HOST
              value: {{ .Values.elasticsearch.env.NETWORK_HOST }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DISCOVERY_SERVICE
              value: {{ .Values.elasticsearch.env.DISCOVERY_SERVICE }}
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
{{ toYaml .Values.elasticsearch.images.resources | indent 12 }}
          volumeMounts:
            - name: wazuh-elasticsearch
              mountPath: /usr/share/elasticsearch/data
            - name: odfe-ssl-certs
              mountPath: /usr/share/elasticsearch/config/node-key.pem
              subPath: node-key.pem
              readOnly: true
            - name: odfe-ssl-certs
              mountPath: /usr/share/elasticsearch/config/node.pem
              subPath: node.pem
              readOnly: true
            - name: odfe-ssl-certs
              mountPath: /usr/share/elasticsearch/config/root-ca.pem
              subPath: root-ca.pem
              readOnly: true
            - name: odfe-ssl-certs
              mountPath: /usr/share/elasticsearch/config/admin.pem
              subPath: admin.pem
              readOnly: true
            - name: odfe-ssl-certs
              mountPath: /usr/share/elasticsearch/config/admin-key.pem
              subPath: admin-key.pem
              readOnly: true
            - name: elastic-odfe-conf
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: config.yml
              readOnly: true
            - name: elastic-odfe-conf
              mountPath: /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
              subPath: internal_users.yml
              readOnly: true
          ports:
            - containerPort: 9200
              name: es-rest
            - containerPort: 9300
              name: es-nodes
  volumeClaimTemplates:
    - metadata:
        name: wazuh-elasticsearch
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: default
        resources:
          requests:
            storage: 50Gi
{{- end -}}